/* token.h */

typedef enum {
        ID = 256, 
	NUM, 
        IF,
	ARRAY,
	BOOLEAN,
	ELSE,
	FALSE,
	TRUE,
	FOR,
	FUNCTION,
	INTEGER,
	PRINT,
	RETURN,
	STRING,
	VOID,
	WHILE,
        LTE,
        EQ,
        GTE,
        NE,
        PP,
        MM,
        AND,
        OR,
        CHAR,
	STR,
	ERROR,
        PLUS = 43,
        MINUS = 45,  
        MUL = 42,  
        DIV = 47,  
        PERCENT = 37,  
        NOT = 33,  
        LT = 60,  
        GT = 62,  
        IS = 61,
        COLON = 58,  
        SEMICOLON = 59,  
        COMMA = 44,  
        LPAREN = 40,  
        RPAREN = 41,  
        LBRACKET = 91,
        RBRACKET = 93,  
        LBRACE = 123,  
        RBRACE = 125
} token_t; 
